### ISSUE TITLE
With multiple assertions per test method use 3-arg version of Assert.assertEquals

### ISSUE THREAD

**Issue by ayco-at-naturalis** [naturalis/naturalis_data_api#10]
https://github.com/naturalis/naturalis_data_api/blob/0a0f9a3c48ef3afc59560563f40e0080dc83f919/nl.naturalis.nba.etl/src/test/java/nl/naturalis/nba/etl/col/CoLTaxonTransformerTest.java#L125-L138

When making multiple assertions per test method, it's better to use the 3-arg version of Assert.assertEquals so you know which assertion caused the failure. E.g.

assertEquals("01", expected1, actual1);
assertEquals("02", expected2, actual2);
assertEquals("03", expected3, actual3);

**Comment by plabon-naturalis** [comment]
Updated setUp(),modifed assert statements to include numbering
