### ISSUE TITLE
Some more unit tests for equalizeNameComponents

### ISSUE THREAD

**Issue by ayco-at-naturalis** [naturalis/naturalis_data_api#11]
https://github.com/naturalis/naturalis_data_api/blob/0a0f9a3c48ef3afc59560563f40e0080dc83f919/nl.naturalis.nba.etl/src/test/java/nl/naturalis/nba/etl/TransformUtilTest.java#L153

There's a lot of branching going on in this method, so it is worth asserting that

1. null values in a ScientificName get the value of the equivalent name component in DefaultClassification
2. null values in a DefaultClassification get the value of the equivalent name component in ScientificName
3. A NameMismatchException is thrown if equivalent name components in ScientificName and DefaultClassification have different (non-null) values

**Comment by plabon-naturalis** [comment]
updated the method accordingly/
